config/routes.rb
Rails.application.routes.draw do
    get '/' => 'site#home'

    # get '/challenges/:id/votes' => 'votes#index'
    # get '/challenges/:id/votes/new' => 'votes#new'

    resources :challenges do
      resources :votes
    end

  end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
	
	mount_uploader :poster, PosterUploader

	has_many :votes, dependent: :destroy #relaciones

	validates :title, presence: true
	validates :description, length: {minimum: 10}
	

end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :challenge

	validates :mail, presence: true
	validates :mail, format: { with: EmailAddressValidator::Regexp::ADDR_SPEC}

	def self.count_mails(id)
		Vote.where('challenge_id = ?', id).count	
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController

	before_filter :load_challenge, only: [:show, :edit, :destroy]

	PER_PAGE = 10

	def index
		search_to_str = params[:q] || ""
	    search_to_str ='%' + search_to_str + '%'
	    @challenges = Challenge.where("title like ?", search_to_str).order(created_at: :desc).paginate(:page => params[:page], :per_page => 10)

	    if params[:page]
			page = params[:page].to_i
			offset = (page-1) * PER_PAGE
			@challenges = @challenges.offset(offset)
		end
	end

	def new
		@challenge = Challenge.new 
	end

	def show
		@vote = @challenge.votes.new
		@total = @challenge.votes.count_mails(params[:id])
	end

	def create
		@challenge = Challenge.create challenge_params
		if @challenge.save
			flash[:notice] = "Challenge create successfully"
			redirect_to challenges_path
		else
			flash[:error] = @challenge.errors.messages
			render 'new'
		end
	end

	def edit
		
	end

	def update
		@challenge = Challenge.find params[:id]
		if @challenge.update_attributes challenge_params 
			flash[:notice] = "Callenge update successfully"
			redirect_to challenges_path
		end
	end
	
	def destroy
		if @challenge.destroy
			flash[:notice] = "Callenge delete successfully"
		end
		redirect_to challenges_path
	end


	private
	
	def challenge_params 
 		params.require(:challenge).permit(:title, :description, :poster)
	end

	def load_challenge
		@challenge = Challenge.find params[:id]
	end

	
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

	def home
		render 'home'
	end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	# def index
	# 	@challenge = Challenge.find params[:id]
	# 	@votes = @challenge.votes
	# end

	# def new
	# 	@challenge = Challenge.find params[:id]
	# 	@vote = @challenge.votes.new
	# end

	# def show

	# end

	def create
		@challenge = Challenge.find params[:challenge_id]
		@vote = @challenge.votes.new vote_params
		if @vote.save
			flash[:notice] = "Vote add successfully"
			UserMailer.new_vote(@challenge,@vote).deliver
			redirect_to challenge_path(params[:challenge_id])
		else
			flash[:error] = "Error"
			redirect_to challenge_path(params[:challenge_id])
		end	
	end

	private
	
	def vote_params 
 		params.require(:vote).permit(:mail)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/challenges/edit.html.erb
<section class="center">
<h1> Edit </h1> 
<%= form_for [@challenge] do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    <%= f.label :poster %>
    <%= f.file_field :poster %>
    <br>
    <%= f.label :description %>
    <%= f.text_area :description %>
    <%= f.submit 'Save' %>
  <% end %>
</section>

app/views/challenges/index.html.erb
<section class="center">
	<div class="flash_success"><%= flash[:notice] %></div>

	<%= form_tag challenges_path, method: :get do %>
 	<%= search_field_tag :q, params[:q], placeholder: "Search a challenge" %>
	<% end %>
	
	<h1> CHALLENGES </h1>
	<% @challenges.each do |c| %>
		<li>
		<%= image_tag c.poster.url(:thumb) %>
		<%= link_to c.title, challenge_path(c) %> -
		<%= c.created_at.strftime("%d %b %y") %>
		<%= link_to("Edit", edit_challenge_path(c)) %>
		</li>
	<% end %>
	<button><%= link_to("Add new challenges", new_challenge_path) %></button>
	 
      <div class="page_info"><%= page_entries_info @challenges %></div>
  
	<div class="apple_pagination"><%= will_paginate @challenges %></div>
	
</section>

app/views/challenges/new.html.erb
<section class="center">
<div class="flash">
<%= flash[:error] %>
</div>

  <h1>New Challenge</h1>
  <%= form_for [@challenge], html: {multipart: true} do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    <%= f.label :poster %>
    <%= f.file_field :poster %>
    <br>
    <%= f.label :description %>
    <%= f.text_area :description %>
    <%= f.submit 'Save' %>
  <% end %>

<section>
 <button><%= link_to("Back to challenges", challenges_path) %></button>
</section>

</section>

app/views/challenges/show.html.erb
<div class="flash_success"><%= flash[:notice] %></div>
<div class="flash"><%= flash[:error] %></div>
<section class="center">

<h1> Challenge </h1>
<div class="title_challenge"><h2>Title</h2><%= @challenge.title %></div><br>
<div class="description_challenge"><b>Description: </b></div>
<div><%= image_tag @challenge.poster.url %></div>
<div><%= @challenge.description %></div>

<h1>Add vote</h1>


<%= form_for [@challenge, @vote] do |f| %>
  <%= f.label :mail %>
  <%= f.text_field :mail %>
  <%= f.submit 'Vote' %>
<% end %>
<div class="votes"><h2>Votes count: <%= @total %></div></h2>
<button><%= link_to("Back", challenges_path) %></button>
 <button><%= link_to("Delete", challenge_path(@challenge), method: :delete, data: {confirm: 'Are you sure?'}) %></button>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Support</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/site/home.html.erb
<section class="center">

	<h1>Challenges</h1>


	<button><%= link_to("Challenges List", challenges_path) %></button>
	<button><%= link_to("Add new challenges", new_challenge_path) %></button>	
	

</section>

app/views/votes/index.html.erb
<% @votes.each do |vote| %>
<%= vote.mail %>

<% end %>

app/views/votes/new.html.erb
<h1>Add votes</h1>